################
##  NFS hosts connection info
##   hosts.yml
##
##  For local installations use `ansible_connection: local`
##  For SSH, fill fields according to:
##    ssh <ansible_user>@<ansible_host>
################
all:
  hosts:
    nfs_server:
      # Connection info for the NFS node
      ansible_host: 161.74.31.112
      ansible_connection: ssh
      ansible_user: ubuntu
